---
- name: Install Reviewboard needed dependencies
  apt: pkg={{item}}
  with_items:
      - python-setuptools
      - python-dev
      - memcached
      - patch
      - python-mysqldb
      - python-psycopg2
      - git-core
      - apache2
      - libapache2-mod-wsgi
      - libjpeg-dev

- name: Install Reviewboard
  easy_install: name={{item}}
  with_items:
    - ReviewBoard
    - pip

- name: install various libraries with pip
  action: pip name={{item}} state=present
  with_items:
    - python-memcached
    - virtualenv
    - supervisor

- name: run reviewboard installer
  sudo: yes
  command: rb-site install {{site_root}}
         --noinput
         --domain-name={{domain_name}}
         --db-type={{db_type}}
         --db-name={{db_name}}
         --db-host={{db_host}}
         --db-user={{db_user}}
         --db-pass={{db_password}}
         --cache-type={{cache_type}}
         --cache-info={{cache_info}}
         --python-loader={{python_loader}}
         --admin-user={{admin_user}}
         --admin-password={{admin_password}}
         --admin-email={{admin_email}}
         --web-server-type={{web_server}}
         --web-server-port={{web_server_port}}
         creates={{site_root}}

- name: Configure Apache
  command: cp {{site_root}}/conf/apache-wsgi.conf /etc/apache2/sites-available/reviewboard
    creates=/etc/apache2/sites-available/reviewboard

- lineinfile: dest=/etc/apache2/ports.conf line="Listen {{web_server_port}}"
- file: path={{site_root}}/data owner=www-data group=www-data mode=0775
- file: path={{site_root}}/htdocs/media/ext owner=www-data group=www-data mode=0775

- name: enable Site
  sudo: yes
  command: a2ensite reviewboard

- name: enable mod_wsgi
  sudo: yes
  command: a2enmod wsgi

- name: restart Apache
  service: name=apache2 state=restarted
