---

- name: ensure database is created
  sudo_user: postgres
  postgresql_db: name={{db_name}}

- name: ensure user does not have unnecessary privilege
  sudo_user: postgres
  postgresql_user: user={{db_user}} password={{db_password}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: ensure user has access to database
  sudo_user: postgres
  postgresql_privs: database={{db_name}} privs=ALL role={{db_user}} objs=ALL_IN_SCHEMA


